name: Build win binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install nexe
        run: npm install -g nexe

      - name: Build binary for windows
        run: npx nexe --build -o myapp-win

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-binary
          path: myapp-win
